language: node_js
node_js:
- 12.22.11
env:
  global:
  - MATTERMOST_CHANNEL=publication
  - secure: ZWqCRBQFCOTUKWeALg7V3fCHODxFrLliHdbAnziDm+/YOylgP7oG7GVUV839QCo10Rl83tRXJJA633ATG3aBImfN0H8S4fF50mpJJetO0Q/jYc4qukeZAyCbkHhwwNpVSrjoNeEFv3eo/nUjExij6RASOUHGBz2cC6oZ7e0kLgOkM60UwRsbIW3wPO0QaXdiYmymlXpPQQUVQHKWSyam0g48oD1zkomfCVkHiFyZQPx51RaziIgd5QBoc5hr4iOUNn9ErktyZUE5vAXJU7zYd4APzwD5k41QRgTkSFlcEQJ2cs6ynry84zS+F4+DKI9edkL8y9vIn98Ggx86BonT/NLyma22neY6QfjHp2KWt+RLmwJOZTKG4J/UeKQiibNUnTEYMFkheNc7qLS922ZIOMLc5Z1V2W/XAgzjJ4Mm9k11vijTN+riOpGpIvQKUb+5QRgf7T997RshuEzU0vaVfW5BYD50DfvUhr/cdgdvVzD8O3nyO3mval9ZtBEtsqY7J+bDzV3L4Cn+CmD+08o4qDA/RUHoDG0uvklUaqoIvhe/zaI74JF2GoVtf1KHSyFv5VQtuIS+NFlRg+wMbzxzNQldUYegHKatzvleB6a6iMpq9OVkWBJvNh4al3dUocAlWdTdH2m7mkCFeZaTJAQhov5SI3zoyVw9e+m6UWXt6lI=
  # MATTERMOST_HOOK_URL
  - secure: iW+0mvaeQGzwd1EU580SLJopbWnL46SumT3Q+655MJR4uRzwVhvCq1RLKaj9m7bFKOTeKfmIAU6s4B+skZ3j4WsgIwE07lwPnHv9sx+2vqtNcB0Y/W05NtK8Q/YtPrmgwKx9Z3o2fLcea+gn54ws95ljAP/MDS0PAtKR8+RfnGIYGlVSKJFjiIICi1uNTFUOxFnZOgTo2P/BAW6wu01iGvLxkYIsrEaKbDyusCp3Ndf7DuT7b3/xirtmaasgq0bClPBBDcFtO5fsn8ZhYQcVySlXmMkXRC9D43wADyBiF4mdXwxuKWlF5A8PefGESE9B1W0gqAAWI9JiKPYyx3KeHOCs4QhNRS8768yKzGuIaZu+c9u3Cb35cWT4t+pRS8ieREgJrEQ759J1KuAvdJ1r1GJ6C5W4EasB0SS3qQ7fr4l4yag1RE4VXvWFUaqz8QDpnjZVza9abAxkpW6PXcaVsMctOitLg7pGXUn5YfWXjleLztlfGXpZPWJPXrJAxMWFUbOHLdddvZ7LNOO+oeKCVO4gVopBSXBwJmvagx/mUaZ8QiSQl1huPWGkSmHbb4yylAEDTYW4ebNIUgRL2J7bRpiR+dHRGZAevWJZZFPxvyehz4sCZfdtlx/HgkefEhVgsqG7KnIpXsy+vkQQ87DfYh7uEos8M3ApdrQiTkLSk0U=
cache:
  yarn: true
  directories:
  - node_modules
branches:
  except:
  - build
  - build-debug
script:
- yarn lint
- yarn build
deploy:
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish
  on:
    branch: ['master','main']
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish --postpublish mattermost
  on:
    tags: true
before_install:
- openssl aes-256-cbc -K $encrypted_8ebb1ef83f64_key -iv $encrypted_8ebb1ef83f64_iv
  -in github_deploy_key.enc -out /tmp/github_deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/github_deploy_key
- ssh-add /tmp/github_deploy_key
after_deploy:
- rm /tmp/github_deploy_key
- ssh-add -D
