language: node_js
node_js:
- 12.22.9
env:
  global:
  - MATTERMOST_CHANNEL=publication
  - secure: CQ44ZVjPAIVRvGgMcduSAX4VmaOrzF3nrJXPFUsNQ2tMVVdaAlI1zTNkdfntqigZgz6Mpk9x+2FcA8qrkNzQ4cW0lPP9f5dBtSH1xetfpXDFKprW4bqzmhgXSXJFTOYxkChOBPmCYJr+Vv4XqDkv/dBEPdfRSgvVyd5YxHSd5HBU91rKyR+Hox7LTnhmlXleLIs11EQgp7RK+L28MBCtCqAa2niFlKKRlqupm2FSpZzxCh9qeY0wKCQzPE+QZUm4waJ1SUGKQwbzAfyOxu2O6rwzaTSknfdJoSX6AMxjRTWBC9c3VfUGM3wjVJIqMhiUj2FQhVIjiDyX/W60/q3UMC5WYzSvEDDfhnKCPwiUKSU7HvSxx9q2YP34evxKo7KPahz9zLlQZvW+GBMyI9hbMDBTALuQVVzhftsvqfrogyYhkEPviiYiVADWNxhacsbUjRA5svXnZvtmCPo7fLFwel/krgC5Z8AwAY0YxWjSHNVScUkieSDCrlxrC09vTtG60unt9gtXbD5ruUkDLWSUwHBv2p0WY1TdP+2Vlf3yYfBvEVbqi59AxG+T17bq7Xv3QZnkrwC+UOCNCeg+gHPv+fRpUaYWzCO4uaoY/nlJa7RulQFhGca3A//6xRo/KgWw9JJnOXJelNjE9oHCUu9xShotUZKOF+O93V/BRqs9ITo=
  - secure: iW+0mvaeQGzwd1EU580SLJopbWnL46SumT3Q+655MJR4uRzwVhvCq1RLKaj9m7bFKOTeKfmIAU6s4B+skZ3j4WsgIwE07lwPnHv9sx+2vqtNcB0Y/W05NtK8Q/YtPrmgwKx9Z3o2fLcea+gn54ws95ljAP/MDS0PAtKR8+RfnGIYGlVSKJFjiIICi1uNTFUOxFnZOgTo2P/BAW6wu01iGvLxkYIsrEaKbDyusCp3Ndf7DuT7b3/xirtmaasgq0bClPBBDcFtO5fsn8ZhYQcVySlXmMkXRC9D43wADyBiF4mdXwxuKWlF5A8PefGESE9B1W0gqAAWI9JiKPYyx3KeHOCs4QhNRS8768yKzGuIaZu+c9u3Cb35cWT4t+pRS8ieREgJrEQ759J1KuAvdJ1r1GJ6C5W4EasB0SS3qQ7fr4l4yag1RE4VXvWFUaqz8QDpnjZVza9abAxkpW6PXcaVsMctOitLg7pGXUn5YfWXjleLztlfGXpZPWJPXrJAxMWFUbOHLdddvZ7LNOO+oeKCVO4gVopBSXBwJmvagx/mUaZ8QiSQl1huPWGkSmHbb4yylAEDTYW4ebNIUgRL2J7bRpiR+dHRGZAevWJZZFPxvyehz4sCZfdtlx/HgkefEhVgsqG7KnIpXsy+vkQQ87DfYh7uEos8M3ApdrQiTkLSk0U=
cache:
  yarn: true
  directories:
  - node_modules
branches:
  except:
  - build
  - build-debug
script:
- yarn lint
- yarn build
deploy:
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish
  on:
    branch: ['master','main']
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish --postpublish mattermost
  on:
    tags: true
before_install:
- openssl aes-256-cbc -K $encrypted_8ebb1ef83f64_key -iv $encrypted_8ebb1ef83f64_iv
  -in github_deploy_key.enc -out /tmp/github_deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/github_deploy_key
- ssh-add /tmp/github_deploy_key
after_deploy:
- rm /tmp/github_deploy_key
- ssh-add -D
